"""empty message

Revision ID: ca3dd2ffdc5e
Revises: 458087fe45ee
Create Date: 2017-02-06 10:51:11.476673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca3dd2ffdc5e'
down_revision = '458087fe45ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_posts',
    sa.Column('category', sa.String(length=12), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('viewed', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('subject', sa.String(length=120), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=30), nullable=False),
    sa.Column('image_ext', sa.String(length=300), nullable=True),
    sa.Column('phone', sa.String(length=12), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('kakaotalk', sa.String(length=30), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=30), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car_posts')
    # ### end Alembic commands ###
